package handlers

import (
	"fmt"
)

/*
	Endpoint: Process Receipts
	Path: /receipts/process
	Method: POST
	Payload: Receipt JSON
	Response: JSON containing an id for the receipt.
	Description:

	Takes in a JSON receipt (see example in the example directory) and returns a JSON object with an ID generated by a function.
	The ID returned is the ID that is passed into /receipts/{id}/points to get the number of points the receipt was awarded.

	Example Response:

	{ "id": "7fb1377b-b223-49d9-a31a-5a02701dd310" }
 */

func ProcessReceipts() {
	fmt.Println("Process Receipts Function: ")
}