package handlers

import (
	"fmt"
	"net/http"
	"github.com/google/uuid" // used to create unique ids
)

/*
	Endpoint: Process Receipts
	Path: /receipts/process
	Method: POST
	Payload: Receipt JSON
	Response: JSON containing an id for the receipt.
	Description:

	Takes in a JSON receipt (see example in the example directory) and returns a JSON object with an ID generated by a function.
	The ID returned is the ID that is passed into /receipts/{id}/points to get the number of points the receipt was awarded.

	Example Response:

	{ "id": "7fb1377b-b223-49d9-a31a-5a02701dd310" }
*/

// uuid function : Universally Unique Identifier – is a 36-character alphanumeric string that used to create unique ids
func ProcessReceipts(res http.ResponseWriter, req *http.Request) {
	enableCors(&res)

	fmt.Println("UUID: ", uuid.New().String())
}